server:
  # consul服务端口
  port: 8006
spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      # consul注册中心地址
      #host: localhost  本地注册中心地址
      host: 192.168.0.107
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
        prefer-ip-address: true

